"""Add AIAnalysisLog table

Revision ID: 8dd7ba8d95e0
Revises: 
Create Date: 2024-02-15 22:18:51.350632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd7ba8d95e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('image_path', sa.String(length=255), nullable=True),
        sa.Column('success', sa.String(length=255), nullable=True),
        sa.Column('message', sa.String(length=255), nullable=True),
        sa.Column('class', sa.Integer(), nullable=True),
        sa.Column('confidence', sa.DECIMAL(5,4), nullable=True),
        sa.Column('request_timestamp', sa.BigInteger(), nullable=True),
        sa.Column('response_timestamp', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis_log')
    # ### end Alembic commands ###